trigger:
  paths:
    include:
    - widget-function/*
    - .azure-pipelines/function.yml
    - .azure-pipelines/templates/*

pr:
  paths:
    include:
    - widget-function/*
    - .azure-pipelines/function.yml
    - .azure-pipelines/templates/*

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.8'
    addToPath: true
    architecture: 'x64'
- bash: pip install -r dev-requirements.txt
  name: InstallDependencies
  workingDirectory: widget-function
- template: templates/test-and-validate.yml
  parameters:
    preCmd: inv
    projectDir: widget-function
    coveragePath: coverage.xml
    buildCmd: lint
